config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items' , to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda {|attrs| attrs['name'].blank?}

  include Placeholder

  validates_presence_of :title, :body, :main_image, :thumb_image

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.angular
    where(subtitle: "Angular")
  end

  def self.by_position
    order("position ASC")
  end

  scope :ruby_on_rails_portfolio_items, -> {where(:subtitle => "Ruby on rails")}

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end


end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout "portfolio"
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :edit, :create, :update, :toggle_status, :sort]}, site_admin: :all
  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find_by_id(value[:id]).update(position: value[:position])
    end
    render nothing: true
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
    3.times {@portfolio_item.technologies.build }
  end
  def create
    @portfolio_item = Portfolio.new(portfolio_params)
    respond_to do |format| if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  def edit
    @portfolio_item = Portfolio.find(params[:id])
  end
  def update
    @portfolio_item = Portfolio.find(params[:id])
    respond_to do |format|
      if @portfolio_item.update(params.require(:portfolio).permit(:title,:body))
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
  def show
    @portfolio_item = Portfolio.find(params[:id])
  end

  def destroy
    @portfolio_item = Portfolio.find(params[:id])
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
end



private
  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :body,
                                      :thumb_image,
                                      :main_image,
                                      technologies_attributes: [:name])
  end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |form| %>
  
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title,class: 'form-control' %>
      </div>

      <div class="form-group">
        <%=form.file_field :main_image %>
      </div>

      <div class="form-group">
        <%=form.file_field :thumb_image %>
      </div>
      
      
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <div class="form-group">
          <%= form.label :body %>
          <%= form.text_area :body,class: 'form-control', rows: 13 %>
        </div>
      </div>
    </div>
  
  <div class="col-md-12">
      <h2>Technologies Used:</h2>
      <div>
        <%= form.fields_for :technologies do | technology_form| %>
          <div class="form-group">
            <%= technology_form.label :name %>
            <%= technology_form.text_field :name,class: 'form-control' %>
          </div>
        <% end %>
      </div>

      <div class="form-group">
        <%= form.submit 'Save Portfolio Item', class: 'btn-primary btn-block'%>
      </div>
  </div>
</div>

<% end %>

app/views/portfolios/_portfolio_item.html.erb
 <div class="card mb-4 box-shadow" data-id="<%= portfolio_item.id %>">
    <%=image_tag portfolio_item.thumb_image.url unless portfolio_item.thumb_image.nil?%>
    <div class="card-body">
      <p class="card-text">
        <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></span> <%= portfolio_item.subtitle%>
      </p>
      <div class="d-flex justify-content-between align-items-center">
        <small class="text-muted">9 mins</small>
      </div>
    </div>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio items</h1>
<% @angular_portfolio_items.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
  <p><%= portfolio_item.subtitle%></p>
  <p><%= portfolio_item.body %></p>
  <%=image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil?%>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item.id) if logged_in?(:site_admin) %>
  <%= link_to 'Delete', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit portfolio item</h1>
  <%= render "form", portfolio_item: @portfolio_item%>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row <%= "sortable" if logged_in?(:site_admin)%>">
      <%= render partial: "portfolio_item", collection: @portfolio_items%>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
  <h1>Create a new portfolio item</h1>
  <%= render "form", portfolio_item: @portfolio_item%>  
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <%=image_tag @portfolio_item.main_image.url, width: "100%" %>
    </div>
    <div class="col-md-7">
      <h1><%=@portfolio_item.title %></h1>
      <hr>
      <em><%=@portfolio_item.body %></em>
      <hr>
      <h3>Technologies Used:</h3>
      <% @portfolio_item.technologies.each do |t|%>
        <p><%= t.name %></p>
      <% end%>
    </div>
  </div>
</div>