config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items' , to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p class="app-footer"><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Sujay Bawaskar</h3>
    <nav class="nav nav-masthead app-nav">
      <%=nav_helper 'nav-link','span'%>
      <%=login_helper 'nav-link'%>
    </nav>

  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator =%>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">An example blog template built with Bootstrap.</p>
    <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <%=nav_helper 'nav-link','span'%>
      <%=login_helper 'nav-link'%>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
     <ol class="list-unstyled social-links">
      <li><a href="#"><%= fa_icon "github" %></a></li>
      <li><a href="#"><%= fa_icon "instagram" %></a></li>
      <li><a href="#"><%= fa_icon "twitter" %></a></li>
    </ol>

  </div>
</div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home",root_path%></div>
  <div><%= link_to "About",about_path%></div>
  <div><%= link_to "Contact",contact_path%></div>
  <div><%= link_to "Blogs",blogs_path%></div>
  <div><%= link_to "Portfolios",portfolios_path%></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to 'View All Portfolio Items', portfolios_path %>/
      <a href="#">Back to top</a>
    </p>
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
   <div class="container">
      <h1 class="jumbotron-heading">My Portfolio</h1>
      <p class="lead text-muted">I'm a passionate computer science engineer with more than 10 years of well-rounded experience in product development, object-oriented design, application integration design, Search engine design and continuous integration. My skills include Java-JEE, Ruby on Rails, Golang and Python. I also have experience with Elasticsearch (ELK) and Apache Solr.</p>
      <p>
        <%= link_to 'Find Out More About Me', about_path, class: 'btn btn-primary my-2'%>
        <%= link_to 'My Blogs', blogs_path, class: 'btn btn-secondary my-2'%>
      </p>
   </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-md-7 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">I'm a passionate computer science engineer with more than 10 years of well-rounded experience in product development, object-oriented design, application integration design, Search engine design and continuous integration. My skills include Java-JEE, Ruby on Rails, Golang and Python. I also have experience with Elasticsearch (ELK) and Apache Solr.</p>
      </div>
      <div class="col-sm-4 offset-md-1 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%=nav_helper 'text-white','li'%>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="navbar navbar-dark bg-dark box-shadow">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand d-flex align-items-center">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
      <strong>Sujay Bawaskar</strong>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>